#!/usr/bin/env bash
# Stage downloaded bottles into the asdf install prefix.
#
# The "relocation" trick: brew bottles use @loader_path-relative dylib
# references like `@loader_path/../../../../opt/<formula>/lib/<dylib>`.
# Four levels up from a binary at `<prefix>/Cellar/<formula>/<version>/bin/`
# lands at `<prefix>/`, so `<prefix>/opt/<formula>` resolves correctly
# when we plant the symlinks. Zero install_name_tool rewrites needed,
# zero codesigning (bottles are already adhoc-signed by brew at build).
#
# Layout under $ASDF_INSTALL_PATH:
#   Cellar/<formula>/<version_revision>/    ← extracted bottle contents
#   opt/<formula> -> ../Cellar/<formula>/<version_revision>
#   bin/php -> ../Cellar/php@<MAJMIN>/<version_revision>/bin/php
#   etc/php/<MAJMIN>/{php.ini,php-fpm.conf,...}  ← from php's .bottle/etc/

set -euo pipefail

# Extract every tarball listed in manifest.txt into Cellar/.
# Args: <install_path> <download_path>
asdf_php_install_extract_all() {
  local install_path="$1" download_path="$2"
  local manifest="$download_path/manifest.txt"
  [[ -f "$manifest" ]] || asdf_php_die "no manifest at $manifest — did bin/download run?"

  mkdir -p "$install_path/Cellar"

  local name tag digest file
  while IFS=' ' read -r name tag digest file; do
    [[ -z "$name" ]] && continue
    local src="$download_path/$file"
    [[ -f "$src" ]] || asdf_php_die "missing tarball $src (from manifest)"
    tar xzf "$src" -C "$install_path/Cellar/"
  done < "$manifest"
}

# For each formula directory under Cellar/<formula>/<version_revision>/,
# create $ASDF_INSTALL_PATH/opt/<formula> → relative symlink.
# Args: <install_path>
asdf_php_install_link_opts() {
  local install_path="$1"
  mkdir -p "$install_path/opt"

  local formula_dir version_dir formula version
  for formula_dir in "$install_path/Cellar/"*; do
    [[ -d "$formula_dir" ]] || continue
    formula="${formula_dir##*/}"

    # Pick the first (and typically only) version dir under this formula.
    for version_dir in "$formula_dir"/*; do
      [[ -d "$version_dir" ]] || continue
      version="${version_dir##*/}"
      ln -snf "../Cellar/${formula}/${version}" "$install_path/opt/${formula}"
      break
    done
  done
}

# Top-level bin/<exe> → tiny wrapper that points PHP at our own etc/ for
# config (otherwise PHP would read the host's brew /opt/homebrew/etc/php/
# because that path is baked into the binary at brew's build time, which
# causes stale extension_dir references and "extension not found" errors).
# Args: <install_path> <majmin>
asdf_php_install_link_bins() {
  local install_path="$1" majmin="$2"
  mkdir -p "$install_path/bin"

  local opt="$install_path/opt/php@${majmin}"
  [[ -d "$opt" ]] || asdf_php_die "expected $opt after staging — php formula didn't extract?"

  local f name
  for f in "$opt/bin/"*; do
    [[ -e "$f" ]] || continue
    name="${f##*/}"
    cat > "$install_path/bin/$name" <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by asdf-php. Routes config + conf.d lookup to this
# install prefix instead of /opt/homebrew/etc/php/${majmin} (which the
# brew bottle baked into the binary at build time). Otherwise PHP picks
# up the host's brew conf.d on machines that have brew installed, which
# brings stale extension_dir references with it.
script_dir="\$(cd -- "\$(dirname -- "\${BASH_SOURCE[0]}")" && pwd)"
prefix="\$(dirname "\$script_dir")"
export PHP_INI_SCAN_DIR="\${PHP_INI_SCAN_DIR:-\$prefix/etc/php/${majmin}/conf.d}"
exec "\$prefix/opt/php@${majmin}/bin/${name}" -c "\$prefix/etc/php/${majmin}" "\$@"
WRAPPER
    chmod +x "$install_path/bin/$name"
  done
}

# Copy default php.ini / php-fpm.conf etc. from the bottle's `.bottle/etc/`,
# rewrite @@HOMEBREW_*@@ placeholders inside those configs, and emit a
# conf.d snippet that loads the shared extensions (intl, opcache) the
# brew bottle built. Without this, php -m omits intl and any zend
# extensions, since the bottle ships .so files but no ini entries that
# point at them.
# Args: <install_path> <majmin>
asdf_php_install_seed_etc() {
  local install_path="$1" majmin="$2"
  local src="$install_path/opt/php@${majmin}/.bottle/etc"

  # 1. Copy bottle's etc/ snapshot (php.ini, php-fpm.conf, pear.conf)
  if [[ -d "$src" ]]; then
    mkdir -p "$install_path/etc"
    cp -R "$src/." "$install_path/etc/"
  fi

  # 2. Rewrite placeholders in every config file we just copied
  find "$install_path/etc" -type f \( -name '*.ini' -o -name '*.conf' \) -print0 \
    | xargs -0 -I {} sed -i '' \
        -e "s|@@HOMEBREW_PREFIX@@|${install_path}|g" \
        -e "s|@@HOMEBREW_CELLAR@@|${install_path}/Cellar|g" {}

  # 3. openssl cert bundle. PHP's php.ini contains
  #      openssl.cafile = "@@HOMEBREW_PREFIX@@/etc/openssl@3/cert.pem"
  #    which we rewrote to <install>/etc/openssl@3/cert.pem — but that
  #    file doesn't exist because ca-certificates is a data-only formula
  #    with no bottle (we skip it in bin/download). brew's own
  #    openssl@3 post_install falls back to symlinking macOS system
  #    certs; do the same. Without this, composer / any PHP SSL client
  #    fails with "failed loading cafile stream".
  if [[ -r /etc/ssl/cert.pem && ! -e "$install_path/etc/openssl@3/cert.pem" ]]; then
    mkdir -p "$install_path/etc/openssl@3"
    ln -snf /etc/ssl/cert.pem  "$install_path/etc/openssl@3/cert.pem"
    ln -snf /etc/ssl/certs     "$install_path/etc/openssl@3/certs"
  fi

  # 4. Generate conf.d/00-asdf-php.ini for the bottle's shared extensions
  local php_lib api_ver ext_dir
  php_lib="$install_path/opt/php@${majmin}/lib/php"
  api_ver="$(find "$php_lib" -maxdepth 1 -type d -name '[0-9]*' -exec basename {} \; | head -1)"
  if [[ -z "$api_ver" ]]; then
    asdf_php_warn "could not find php extension API dir under $php_lib"
    return 0
  fi
  ext_dir="$php_lib/$api_ver"

  local conf_d="$install_path/etc/php/${majmin}/conf.d"
  mkdir -p "$conf_d"
  {
    echo "; Auto-generated by asdf-php. Points extension_dir at this install's"
    echo "; bottle and registers the shared extensions the bottle shipped."
    echo "extension_dir = \"${ext_dir}\""
    local so name
    for so in "$ext_dir"/*.so; do
      [[ -e "$so" ]] || continue
      name="$(basename "$so" .so)"
      case "$name" in
        opcache) echo "zend_extension=${name}.so" ;;
        *)       echo "extension=${name}.so" ;;
      esac
    done
  } > "$conf_d/00-asdf-php.ini"
}

# Drop the latest stable composer phar at <install>/bin/composer so
# users get `composer` alongside `php` with no extra step. Composer's
# `#!/usr/bin/env php` shebang picks up our <install>/bin/php wrapper
# via mise's shim PATH.
#
# Opt out by setting ASDF_PHP_BUNDLE_COMPOSER=0. Composer version pins
# per-project via .tool-versions would need a separate asdf-composer
# plugin — deliberately out of scope; see TODO.md.
# Args: <install_path>
asdf_php_install_bundle_composer() {
  local install_path="$1"

  if [[ "${ASDF_PHP_BUNDLE_COMPOSER:-1}" == "0" ]]; then
    return 0
  fi

  local dest="$install_path/bin/composer"
  local url="https://getcomposer.org/composer-stable.phar"

  if ! curl -fsSL "$url" -o "$dest" 2>/dev/null; then
    asdf_php_warn "composer download failed; skipping (set ASDF_PHP_BUNDLE_COMPOSER=0 to silence)"
    rm -f "$dest"
    return 0
  fi
  chmod +x "$dest"

  # Probe version through our wrapper so composer's `env php` shebang
  # doesn't accidentally pick up an unrelated system PHP mid-install.
  local ver
  ver="$("$install_path/bin/php" "$dest" --version 2>/dev/null | awk '/^Composer/ {print $3; exit}')" \
    || ver="(unknown)"
  asdf_php_log "bundled composer $ver"
}

# Sanity-check: php --version runs and reports the expected version.
# Args: <install_path> <expected_version>
asdf_php_install_verify() {
  local install_path="$1" want="$2"
  local php="$install_path/bin/php"
  [[ -x "$php" ]] || asdf_php_die "no executable at $php"
  local got
  got="$("$php" --version 2>&1 | head -1)" \
    || asdf_php_die "php --version failed: $got"
  if [[ "$got" != *"$want"* ]]; then
    asdf_php_die "php --version reports unexpected version: $got (wanted $want)"
  fi
  asdf_php_log "verified: $got"
}
