#!/usr/bin/env bash
# Stage downloaded bottles into the asdf install prefix.
#
# The "relocation" trick: brew bottles use @loader_path-relative dylib
# references like `@loader_path/../../../../opt/<formula>/lib/<dylib>`.
# Four levels up from a binary at `<prefix>/Cellar/<formula>/<version>/bin/`
# lands at `<prefix>/`, so `<prefix>/opt/<formula>` resolves correctly
# when we plant the symlinks. Zero install_name_tool rewrites needed,
# zero codesigning (bottles are already adhoc-signed by brew at build).
#
# Layout under $ASDF_INSTALL_PATH:
#   Cellar/<formula>/<version_revision>/    ← extracted bottle contents
#   opt/<formula> -> ../Cellar/<formula>/<version_revision>
#   bin/php -> ../Cellar/php@<MAJMIN>/<version_revision>/bin/php
#   etc/php/<MAJMIN>/{php.ini,php-fpm.conf,...}  ← from php's .bottle/etc/

set -euo pipefail

# Extract every tarball listed in manifest.txt into Cellar/.
# Args: <install_path> <download_path>
asdf_php_install_extract_all() {
  local install_path="$1" download_path="$2"
  local manifest="$download_path/manifest.txt"
  [[ -f "$manifest" ]] || asdf_php_die "no manifest at $manifest — did bin/download run?"

  mkdir -p "$install_path/Cellar"

  local name _tag _digest file
  while IFS=' ' read -r name _tag _digest file; do
    [[ -z "$name" ]] && continue
    local src="$download_path/$file"
    [[ -f "$src" ]] || asdf_php_die "missing tarball $src (from manifest)"
    tar xzf "$src" -C "$install_path/Cellar/"
  done < "$manifest"
}

# For each formula directory under Cellar/<formula>/<version_revision>/,
# create $ASDF_INSTALL_PATH/opt/<formula> → relative symlink.
# Args: <install_path>
asdf_php_install_link_opts() {
  local install_path="$1"
  mkdir -p "$install_path/opt"

  local formula_dir version_dir formula version
  for formula_dir in "$install_path/Cellar/"*; do
    [[ -d "$formula_dir" ]] || continue
    formula="${formula_dir##*/}"

    # Pick the first (and typically only) version dir under this formula.
    for version_dir in "$formula_dir"/*; do
      [[ -d "$version_dir" ]] || continue
      version="${version_dir##*/}"
      ln -snf "../Cellar/${formula}/${version}" "$install_path/opt/${formula}"
      break
    done
  done
}

# Top-level bin/<exe> → tiny wrapper that points PHP at our own etc/ for
# config (otherwise PHP would read the host's brew /opt/homebrew/etc/php/
# because that path is baked into the binary at brew's build time, which
# causes stale extension_dir references and "extension not found" errors).
# Args: <install_path> <majmin>
asdf_php_install_link_bins() {
  local install_path="$1" majmin="$2"
  mkdir -p "$install_path/bin"

  local opt="$install_path/opt/php@${majmin}"
  [[ -d "$opt" ]] || asdf_php_die "expected $opt after staging — php formula didn't extract?"

  local f name
  for f in "$opt/bin/"*; do
    [[ -e "$f" ]] || continue
    name="${f##*/}"

    # Skip `phar` (symlink → phar.phar) and `phar.phar` entirely.
    # Their shebang carries @@HOMEBREW_CELLAR@@ hardcoded, AND the
    # archive's tail-appended SHA1 signature was computed by brew for
    # the resolved-path shebang (which brew fixes up in post_install).
    # Since we don't run brew, both the shebang and the signature are
    # broken for our install — Phar::mapPhar() throws
    # "SHA1 signature could not be verified" no matter which way we
    # invoke the file. Users who need phar CLI can use `php` against
    # their own phar files via the Phar:: API.
    if [[ "$name" == "phar" || "$name" == "phar.phar" ]]; then
      continue
    fi

    cat > "$install_path/bin/$name" <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by asdf-php. Routes config + conf.d lookup to this
# install prefix instead of /opt/homebrew/etc/php/${majmin} (which the
# brew bottle baked into the binary at build time). Otherwise PHP picks
# up the host's brew conf.d on machines that have brew installed, which
# brings stale extension_dir references with it.
#
# We use PHPRC + PHP_INI_SCAN_DIR env vars rather than passing -c to the
# binary, because non-php scripts (pecl, pear, phpize) also live under
# bin/ and forward args to peclcmd.php etc. — those interpret -c as
# PEAR's config-file path and blow up ("<dir> is not a valid config file").
# Env vars are only read by the php binary itself; wrapping stays uniform.
script_dir="\$(cd -- "\$(dirname -- "\${BASH_SOURCE[0]}")" && pwd)"
prefix="\$(dirname "\$script_dir")"
export PHPRC="\${PHPRC:-\$prefix/etc/php/${majmin}/php.ini}"
export PHP_INI_SCAN_DIR="\${PHP_INI_SCAN_DIR:-\$prefix/etc/php/${majmin}/conf.d}"
# PEAR/pecl reads pear.conf from \$PHP_PEAR_SYSCONF_DIR, else the
# compile-time PHP_SYSCONFDIR baked into the binary (= /opt/homebrew/etc/php/…
# from brew's build). Without this, pecl config-get ext_dir returns brew's
# path and pecl-installed .so files land outside our prefix.
export PHP_PEAR_SYSCONF_DIR="\${PHP_PEAR_SYSCONF_DIR:-\$prefix/etc/php/${majmin}}"
# When the snmp extension is loaded (default on 8.6+), libnetsnmp_init
# writes "MIB search path: <compiled-in>" + a wall of "Cannot find
# module (X-MIB)" to stderr if the compiled-in MIBDIRS path (baked in
# at brew's build → /opt/homebrew/Cellar/net-snmp/…/share/snmp/mibs)
# doesn't exist on the host. Point MIBDIRS at the bundled MIBs; fall
# back to disabling MIB parsing if net-snmp wasn't bundled with this
# PHP version. Users who need custom MIBs override either var.
if [[ -d "\$prefix/opt/net-snmp/share/snmp/mibs" ]]; then
  export MIBDIRS="\${MIBDIRS-\$prefix/opt/net-snmp/share/snmp/mibs}"
else
  export MIBS="\${MIBS-}"
fi
exec "\$prefix/opt/php@${majmin}/bin/${name}" "\$@"
WRAPPER
    chmod +x "$install_path/bin/$name"
  done

  # Drop the extension-manager helper alongside php/composer, with the
  # plugin's lib/ path baked in so `asdf-php-ext install` can source
  # formula/ghcr/relocate/deps at runtime. list/enable/disable stay
  # self-contained and work even if the plugin is later uninstalled.
  local plugin_dir
  plugin_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
  if [[ -f "$plugin_dir/share/asdf-php-ext" ]]; then
    sed "s|__PLUGIN_LIB_DIR__|${plugin_dir}/lib|" \
      "$plugin_dir/share/asdf-php-ext" > "$install_path/bin/asdf-php-ext"
    chmod +x "$install_path/bin/asdf-php-ext"
  fi

  # ini setting helper: user-writable settings land in
  # conf.d/99-asdf-php-user.ini (loads last, wins). Fully self-contained,
  # no plugin lib dependency.
  if [[ -f "$plugin_dir/share/asdf-php-ini" ]]; then
    cp "$plugin_dir/share/asdf-php-ini" "$install_path/bin/asdf-php-ini"
    chmod +x "$install_path/bin/asdf-php-ini"
  fi

  # Shell completions for the asdf-php-* helpers. Ship into
  # <install>/share/completions/ so users can point their zsh $fpath
  # (or bash-completion.d) at that dir. Bundled per install rather
  # than installed globally to avoid polluting the user's shell config
  # from a plugin script.
  if [[ -d "$plugin_dir/share/completions" ]]; then
    mkdir -p "$install_path/share/completions"
    cp -R "$plugin_dir/share/completions/." "$install_path/share/completions/"
  fi
}

# Copy default php.ini / php-fpm.conf etc. from the bottle's `.bottle/etc/`,
# rewrite @@HOMEBREW_*@@ placeholders inside those configs, and emit a
# conf.d snippet that loads the shared extensions (intl, opcache) the
# brew bottle built. Without this, php -m omits intl and any zend
# extensions, since the bottle ships .so files but no ini entries that
# point at them.
# Args: <install_path> <majmin>
asdf_php_install_seed_etc() {
  local install_path="$1" majmin="$2"
  local src="$install_path/opt/php@${majmin}/.bottle/etc"

  # 1. Copy bottle's etc/ snapshot (php.ini, php-fpm.conf, pear.conf)
  if [[ -d "$src" ]]; then
    mkdir -p "$install_path/etc"
    cp -R "$src/." "$install_path/etc/"
  fi

  # 2. Rewrite placeholders in every config file we just copied
  find "$install_path/etc" -type f \( -name '*.ini' -o -name '*.conf' \) -print0 \
    | xargs -0 -I {} sed -i '' \
        -e "s|@@HOMEBREW_PREFIX@@|${install_path}|g" \
        -e "s|@@HOMEBREW_CELLAR@@|${install_path}/Cellar|g" {}

  # 2a. PEAR .reg files: substitute @@HOMEBREW_CELLAR@@ with our
  # install's Cellar path AND recompute `s:N:` length prefixes.
  #
  # Diagnosis: brew's post_install patches these files by replacing
  # `@@HOMEBREW_CELLAR@@` (19 chars) with `/opt/homebrew/Cellar`
  # (20 chars). The `s:N:` prefixes in the shipped bottle are baked
  # for the resolved brew path (N = placeholder-value-length + 1).
  # Left untouched, unserialize fails at the first placeholder site
  # and PEAR / pecl emit noisy Notice: unserialize() errors on every
  # registry-touching operation.
  #
  # Fixing with sed + perl-length-recompute isn't safe: general
  # serialize values can contain `"`, breaking the naive regex. But
  # .reg values are paths (no `"`), so a bounded regex works if we
  # anchor on the `s:N:"..."` shape. We use `preg_replace_callback`
  # in PHP so length recomputation is done from the actual byte length.
  # shellcheck disable=SC2125  # intentional glob-in-assignment; expanded in `for`
  local reg_glob="$install_path/Cellar/php@${majmin}"/*/share/php@${majmin}/pear
  local reg_php='
    $cellar = $argv[1];
    foreach ([$argv[2]."/.registry", $argv[2]."/.channels", $argv[2]."/.channels/.alias"] as $dir) {
      if (!is_dir($dir)) continue;
      foreach (glob("$dir/*.reg") as $f) {
        $data = file_get_contents($f);
        $out = preg_replace_callback(
          "/s:(\d+):\"([^\"]*?)@@HOMEBREW_CELLAR@@([^\"]*?)\";/",
          function ($m) use ($cellar) {
            $v = $m[2] . $cellar . $m[3];
            return "s:" . strlen($v) . ":\"" . $v . "\";";
          },
          $data
        );
        if ($out !== $data) file_put_contents($f, $out);
      }
    }
  '
  # Only run if the pear dir exists (older bottles skipped PEAR).
  local pear_dir
  for pear_dir in $reg_glob; do
    [[ -d "$pear_dir" ]] || continue
    "$install_path/opt/php@${majmin}/bin/php" -r "$reg_php" -- \
      "$install_path/Cellar" "$pear_dir"
    break
  done

  # 2b. pear.conf is PHP-serialized (`a:N:{s:K:"key";s:V:"value";...}`),
  # not a plain text config. Step 2's sed rewrote path values but not
  # the `s:V:` length prefixes, so unserialize() silently fails and PEAR
  # falls back to compiled-in DEFAULTS — which point at brew's paths
  # (/opt/homebrew/*). That in turn makes `pecl install X` drop the .so
  # in brew's tree instead of ours, and `asdf-php-ext enable X` can't
  # find it. Recompute the `s:N:` length prefixes to match the rewritten
  # values.
  local pear_conf="$install_path/etc/php/${majmin}/pear.conf"
  if [[ -f "$pear_conf" ]]; then
    LC_ALL=C perl -i -pe 's{s:\d+:"([^"]*)"}{"s:".length($1).":\"$1\""}ge' \
      "$pear_conf"
  fi

  # 3. openssl cert bundle. PHP's php.ini contains
  #      openssl.cafile = "@@HOMEBREW_PREFIX@@/etc/openssl@3/cert.pem"
  #    which we rewrote to <install>/etc/openssl@3/cert.pem — but that
  #    file doesn't exist because ca-certificates is a data-only formula
  #    with no bottle (we skip it in bin/download). brew's own
  #    openssl@3 post_install falls back to symlinking macOS system
  #    certs; do the same. Without this, composer / any PHP SSL client
  #    fails with "failed loading cafile stream".
  if [[ -r /etc/ssl/cert.pem && ! -e "$install_path/etc/openssl@3/cert.pem" ]]; then
    mkdir -p "$install_path/etc/openssl@3"
    ln -snf /etc/ssl/cert.pem  "$install_path/etc/openssl@3/cert.pem"
    ln -snf /etc/ssl/certs     "$install_path/etc/openssl@3/certs"
  fi

  # 4. Unify the extension_dir on the pecl/ path.
  #
  # brew's PHP keg has TWO extension dirs:
  #   <keg>/lib/php/<api>/   — bundled shared .so (opcache, intl, ...)
  #   <keg>/pecl/<api>/      — where `pecl install X` compiles new .so
  # `php-config --extension-dir` (which pecl reads) reports the pecl/
  # path. So without intervention: pecl installs land in pecl/, our
  # extension_dir points at lib/php/, PHP loads bundled extensions but
  # not pecl'd ones, and `asdf-php-ext enable X` for a pecl'd extension
  # fails to find its .so.
  # brew papers over this by symlinking <prefix>/lib/php/pecl/<api> →
  # <keg>/pecl/<api> during post_install. We do the equivalent locally:
  # symlink bundled .so files into pecl/<api>/ and set extension_dir
  # there. One dir, both origins.
  # Derive the pecl extension_dir from php-config, which is authoritative
  # (baked at brew build time, then relocated by relocate_text_scripts).
  # Previously we globbed `lib/php/<api>/` for the API version and built
  # our own `pecl/<api>/` path, which broke on 8.6 where the extension_dir
  # baked into php-config didn't match a single glob-visible dir under
  # lib/php.
  local php_config ext_dir api_ver pecl_dir
  php_config="$install_path/opt/php@${majmin}/bin/php-config"
  [[ -x "$php_config" ]] || asdf_php_die "no php-config at $php_config after relocation"
  pecl_dir="$("$php_config" --extension-dir 2>/dev/null)" \
    || asdf_php_die "php-config --extension-dir failed"
  [[ -n "$pecl_dir" ]] || asdf_php_die "php-config --extension-dir returned empty"
  api_ver="${pecl_dir##*/}"
  mkdir -p "$pecl_dir"

  # Symlink bundled .so files into pecl_dir. Bottles ship them at one
  # of two paths depending on the formula's era:
  #   - 8.1/8.2/8.3-style: <keg>/lib/php/<api>/*.so
  #   - 8.6+ style:        <keg>/lib/php/pecl/<api>/*.so
  # Try both. If neither has files, dump a listing so future breakage
  # is diagnosable from CI logs.
  local keg="$install_path/opt/php@${majmin}"
  local bundled_dir="" candidate
  for candidate in "$keg/lib/php/${api_ver}" "$keg/lib/php/pecl/${api_ver}"; do
    if [[ -d "$candidate" ]] && compgen -G "$candidate/*.so" >/dev/null; then
      bundled_dir="$candidate"
      break
    fi
  done
  if [[ -n "$bundled_dir" ]]; then
    local bundled_so rel
    for bundled_so in "$bundled_dir"/*.so; do
      [[ -e "$bundled_so" ]] || continue
      # Compute the pecl_dir → bundled_so relative link.
      rel="$(python3 -c "import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))" \
        "$bundled_so" "$pecl_dir" 2>/dev/null)" || rel="$bundled_so"
      ln -snf "$rel" "$pecl_dir/${bundled_so##*/}"
    done
  else
    asdf_php_warn "no bundled .so found under $keg/lib/php/{$api_ver,pecl/$api_ver}"
    asdf_php_warn "keg layout under lib/php:"
    find "$keg/lib/php" -maxdepth 3 -print 2>&1 | head -20 | while read -r line; do
      asdf_php_warn "  $line"
    done
  fi
  ext_dir="$pecl_dir"

  local conf_d="$install_path/etc/php/${majmin}/conf.d"
  mkdir -p "$conf_d"

  cat > "$conf_d/00-asdf-php.ini" <<INI
; Auto-generated by asdf-php. Points extension_dir at this install's
; bottle. Do not remove — needed for enable/disable to find .so files.
extension_dir = "${ext_dir}"
INI

  local so name directive
  for so in "$ext_dir"/*.so; do
    [[ -e "$so" ]] || continue
    name="$(basename "$so" .so)"
    case "$name" in
      opcache|xdebug|xhprof|blackfire) directive=zend_extension ;;
      *)                               directive=extension ;;
    esac
    printf '%s\n' "${directive}=${name}.so" > "$conf_d/10-${name}.ini"
  done
}

# Drop the latest stable composer phar at <install>/bin/composer as a
# raw phar (chmod +x, no wrapper). Composer's `#!/usr/bin/env php`
# shebang resolves `php` from PATH, so composer follows whatever PHP
# mise resolves in the cwd (the same semantics as every other shim'd
# tool). Users invoking from a directory that pins an uninstalled PHP
# see mise's usual "Tool not installed for shim" error; that's the
# same UX as any other mise-managed binary, not an asdf-php bug.
#
# Composer 2.x supports PHP 7.2 through 8.4, so a single phar works
# for any install, and the phar auto-updates via `composer self-update`.
#
# Opt out with ASDF_PHP_BUNDLE_COMPOSER=0.
# Args: <install_path> <majmin>
asdf_php_install_bundle_composer() {
  local install_path="$1" majmin="$2"

  if [[ "${ASDF_PHP_BUNDLE_COMPOSER:-1}" == "0" ]]; then
    return 0
  fi

  local dest="$install_path/bin/composer"
  local url="https://getcomposer.org/composer-stable.phar"

  if ! curl -fsSL "$url" -o "$dest" 2>/dev/null; then
    asdf_php_warn "composer download failed; skipping (set ASDF_PHP_BUNDLE_COMPOSER=0 to silence)"
    rm -f "$dest"
    return 0
  fi
  chmod +x "$dest"

  # Probe version through THIS install's php explicitly so the log
  # line reports composer against the php we just staged, not against
  # whatever mise happens to resolve in the install-time cwd.
  local ver
  ver="$("$install_path/opt/php@${majmin}/bin/php" "$dest" --version 2>/dev/null \
        | awk '/^Composer/ {print $3; exit}')" \
    || ver="(unknown)"
  asdf_php_log "bundled composer $ver"
}

# Sanity-check: php --version runs and reports the expected version.
# Args: <install_path> <expected_version>
#
# Extension init sometimes writes to stderr (e.g. net-snmp prints its
# "MIB search path" line on load if MIBDIRS points at a nonexistent
# path). Grep for the `PHP X.Y.Z` line explicitly instead of `head -1`
# so the check doesn't fail on that pollution.
asdf_php_install_verify() {
  local install_path="$1" want="$2"
  local php="$install_path/bin/php"
  [[ -x "$php" ]] || asdf_php_die "no executable at $php"
  local out got
  out="$("$php" --version 2>&1)" \
    || asdf_php_die "php --version exited non-zero: $out"
  got="$(printf '%s\n' "$out" | grep -m1 '^PHP ' || true)"
  [[ -n "$got" ]] || asdf_php_die "php --version produced no version line: $out"
  if [[ "$got" != *"$want"* ]]; then
    asdf_php_die "php --version reports unexpected version: $got (wanted $want)"
  fi
  asdf_php_log "verified: $got"
}
